//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilioApplication.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewRegistration
    {
        public string Phonenumber { get; set; }
        public int phid { get; set; }
    }
}
