//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilioApplication.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class participatingindividual
    {
        public int recordid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string pseudonym { get; set; }
        public string FoodPreferences { get; set; }
        public string DietaryRestrictions { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string sendphone { get; set; }
        public string status { get; set; }
        public string participatingfor { get; set; }
        public string bread { get; set; }
        public string cheese { get; set; }
        public string veggies { get; set; }
        public string sauces { get; set; }
        public string Seasonings { get; set; }
        public string drinks { get; set; }
        public string sides { get; set; }
        public string lunchmenu { get; set; }
    }
}
