//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilioApplication.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class saucesmenu
    {
        public int saucesmenuid { get; set; }
        public string choiceofmenu { get; set; }
        public string active { get; set; }
        public Nullable<int> choice { get; set; }
    }
}
