//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilioApplication.Models.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class smsblast
    {
        public int blastid { get; set; }
        public Nullable<int> recordid { get; set; }
        public string phonenumber { get; set; }
        public Nullable<System.DateTime> recorddate { get; set; }
        public string participatingfor { get; set; }
        public string breakfastsmssent { get; set; }
        public Nullable<System.DateTime> breakfastsentdatetime { get; set; }
        public string lunchsmssent { get; set; }
        public Nullable<System.DateTime> lunchsentdatetime { get; set; }
        public string participatelunch { get; set; }
        public string participatebreakfast { get; set; }
        public string newregisteration { get; set; }
    }
}
