//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilioApplication.Models.EDMXModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class twilioEntities : DbContext
    {
        public twilioEntities()
            : base("name=twilioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bread> breads { get; set; }
        public DbSet<cheesemenu> cheesemenus { get; set; }
        public DbSet<dietaryrestsriction> dietaryrestsrictions { get; set; }
        public DbSet<drinksmenu> drinksmenus { get; set; }
        public DbSet<foodmenu> foodmenus { get; set; }
        public DbSet<lunchmenu> lunchmenus { get; set; }
        public DbSet<NewRegistration> NewRegistrations { get; set; }
        public DbSet<NewRegnentry> NewRegnentries { get; set; }
        public DbSet<participatingindividual> participatingindividuals { get; set; }
        public DbSet<participatinglocation> participatinglocations { get; set; }
        public DbSet<receivedtransaction> receivedtransactions { get; set; }
        public DbSet<saucesmenu> saucesmenus { get; set; }
        public DbSet<seasoningsmenu> seasoningsmenus { get; set; }
        public DbSet<senttransaction> senttransactions { get; set; }
        public DbSet<sidesmenu> sidesmenus { get; set; }
        public DbSet<smsblast> smsblasts { get; set; }
        public DbSet<tbl_user> tbl_user { get; set; }
        public DbSet<transactionstatu> transactionstatus { get; set; }
        public DbSet<veggiesmenu> veggiesmenus { get; set; }
    
        public virtual ObjectResult<string> bkp_sp_receivedmessages(string phone, string choice, string returnmessage)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var choiceParameter = choice != null ?
                new ObjectParameter("choice", choice) :
                new ObjectParameter("choice", typeof(string));
    
            var returnmessageParameter = returnmessage != null ?
                new ObjectParameter("returnmessage", returnmessage) :
                new ObjectParameter("returnmessage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("bkp_sp_receivedmessages", phoneParameter, choiceParameter, returnmessageParameter);
        }
    
        public virtual ObjectResult<sp_breakfastmessagessend_Result> sp_breakfastmessagessend(ObjectParameter phone, string sentmessage)
        {
            var sentmessageParameter = sentmessage != null ?
                new ObjectParameter("sentmessage", sentmessage) :
                new ObjectParameter("sentmessage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_breakfastmessagessend_Result>("sp_breakfastmessagessend", phone, sentmessageParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_CheckUser(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_CheckUser", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_getfoodmenudetails_Result> sp_getfoodmenudetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getfoodmenudetails_Result>("sp_getfoodmenudetails");
        }
    
        public virtual ObjectResult<sp_getorderstatus_Result> sp_getorderstatus(string transtype)
        {
            var transtypeParameter = transtype != null ?
                new ObjectParameter("transtype", transtype) :
                new ObjectParameter("transtype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getorderstatus_Result>("sp_getorderstatus", transtypeParameter);
        }
    
        public virtual int sp_getorderstatusinsertrecord(string phonenumber, string trantype, string username)
        {
            var phonenumberParameter = phonenumber != null ?
                new ObjectParameter("phonenumber", phonenumber) :
                new ObjectParameter("phonenumber", typeof(string));
    
            var trantypeParameter = trantype != null ?
                new ObjectParameter("trantype", trantype) :
                new ObjectParameter("trantype", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getorderstatusinsertrecord", phonenumberParameter, trantypeParameter, usernameParameter);
        }
    
        public virtual ObjectResult<sp_getorderstatusrecorddetails_Result> sp_getorderstatusrecorddetails(string phonenumber, string transtype)
        {
            var phonenumberParameter = phonenumber != null ?
                new ObjectParameter("phonenumber", phonenumber) :
                new ObjectParameter("phonenumber", typeof(string));
    
            var transtypeParameter = transtype != null ?
                new ObjectParameter("transtype", transtype) :
                new ObjectParameter("transtype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getorderstatusrecorddetails_Result>("sp_getorderstatusrecorddetails", phonenumberParameter, transtypeParameter);
        }
    
        public virtual ObjectResult<sp_getorderstatusrecordlogdetails_Result> sp_getorderstatusrecordlogdetails(string phonenumber, string transtype)
        {
            var phonenumberParameter = phonenumber != null ?
                new ObjectParameter("phonenumber", phonenumber) :
                new ObjectParameter("phonenumber", typeof(string));
    
            var transtypeParameter = transtype != null ?
                new ObjectParameter("transtype", transtype) :
                new ObjectParameter("transtype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getorderstatusrecordlogdetails_Result>("sp_getorderstatusrecordlogdetails", phonenumberParameter, transtypeParameter);
        }
    
        public virtual ObjectResult<sp_getorderstatustotals_Result> sp_getorderstatustotals(string trantype)
        {
            var trantypeParameter = trantype != null ?
                new ObjectParameter("trantype", trantype) :
                new ObjectParameter("trantype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getorderstatustotals_Result>("sp_getorderstatustotals", trantypeParameter);
        }
    
        public virtual ObjectResult<sp_getparticipatingindividuals_Result> sp_getparticipatingindividuals()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getparticipatingindividuals_Result>("sp_getparticipatingindividuals");
        }
    
        public virtual ObjectResult<sp_getparticipatinglocations_Result> sp_getparticipatinglocations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getparticipatinglocations_Result>("sp_getparticipatinglocations");
        }
    
        public virtual ObjectResult<sp_getuserdetails_Result> sp_getuserdetails(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getuserdetails_Result>("sp_getuserdetails", useridParameter);
        }
    
        public virtual ObjectResult<sp_getuserlist_Result> sp_getuserlist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getuserlist_Result>("sp_getuserlist");
        }
    
        public virtual int sp_insertblast(Nullable<int> recordid, string phonenumber, string participatingfor)
        {
            var recordidParameter = recordid.HasValue ?
                new ObjectParameter("recordid", recordid) :
                new ObjectParameter("recordid", typeof(int));
    
            var phonenumberParameter = phonenumber != null ?
                new ObjectParameter("phonenumber", phonenumber) :
                new ObjectParameter("phonenumber", typeof(string));
    
            var participatingforParameter = participatingfor != null ?
                new ObjectParameter("participatingfor", participatingfor) :
                new ObjectParameter("participatingfor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertblast", recordidParameter, phonenumberParameter, participatingforParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_insertupdatefoodmenudetails(Nullable<int> foodmenuid, string menufor, string choiceofmenu, string active, Nullable<int> choice)
        {
            var foodmenuidParameter = foodmenuid.HasValue ?
                new ObjectParameter("foodmenuid", foodmenuid) :
                new ObjectParameter("foodmenuid", typeof(int));
    
            var menuforParameter = menufor != null ?
                new ObjectParameter("menufor", menufor) :
                new ObjectParameter("menufor", typeof(string));
    
            var choiceofmenuParameter = choiceofmenu != null ?
                new ObjectParameter("choiceofmenu", choiceofmenu) :
                new ObjectParameter("choiceofmenu", typeof(string));
    
            var activeParameter = active != null ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(string));
    
            var choiceParameter = choice.HasValue ?
                new ObjectParameter("choice", choice) :
                new ObjectParameter("choice", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_insertupdatefoodmenudetails", foodmenuidParameter, menuforParameter, choiceofmenuParameter, activeParameter, choiceParameter);
        }
    
        public virtual int sp_insertupdatepartipatinglocations(Nullable<int> locationid, string locationaddress, string participatingfor, Nullable<int> displayorder, Nullable<int> choice, string active)
        {
            var locationidParameter = locationid.HasValue ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(int));
    
            var locationaddressParameter = locationaddress != null ?
                new ObjectParameter("locationaddress", locationaddress) :
                new ObjectParameter("locationaddress", typeof(string));
    
            var participatingforParameter = participatingfor != null ?
                new ObjectParameter("participatingfor", participatingfor) :
                new ObjectParameter("participatingfor", typeof(string));
    
            var displayorderParameter = displayorder.HasValue ?
                new ObjectParameter("displayorder", displayorder) :
                new ObjectParameter("displayorder", typeof(int));
    
            var choiceParameter = choice.HasValue ?
                new ObjectParameter("choice", choice) :
                new ObjectParameter("choice", typeof(int));
    
            var activeParameter = active != null ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertupdatepartipatinglocations", locationidParameter, locationaddressParameter, participatingforParameter, displayorderParameter, choiceParameter, activeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_insertupdateuserlist(Nullable<int> userid, string username, string password, string firstname, string lastname, string email, string status)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_insertupdateuserlist", useridParameter, usernameParameter, passwordParameter, firstnameParameter, lastnameParameter, emailParameter, statusParameter);
        }
    
        public virtual int sp_insnewregnphone(string phonenumbers)
        {
            var phonenumbersParameter = phonenumbers != null ?
                new ObjectParameter("phonenumbers", phonenumbers) :
                new ObjectParameter("phonenumbers", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insnewregnphone", phonenumbersParameter);
        }
    
        public virtual int sp_logsenttransactions(string phone, string msgsentfor, string msgsent)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var msgsentforParameter = msgsentfor != null ?
                new ObjectParameter("msgsentfor", msgsentfor) :
                new ObjectParameter("msgsentfor", typeof(string));
    
            var msgsentParameter = msgsent != null ?
                new ObjectParameter("msgsent", msgsent) :
                new ObjectParameter("msgsent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_logsenttransactions", phoneParameter, msgsentforParameter, msgsentParameter);
        }
    
        public virtual ObjectResult<sp_lunchmessagessend_Result> sp_lunchmessagessend(ObjectParameter phone, string sentmessage)
        {
            var sentmessageParameter = sentmessage != null ?
                new ObjectParameter("sentmessage", sentmessage) :
                new ObjectParameter("sentmessage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lunchmessagessend_Result>("sp_lunchmessagessend", phone, sentmessageParameter);
        }
    
        public virtual ObjectResult<sp_messagessend_Result> sp_messagessend(string type, ObjectParameter phone, string sentmessage)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var sentmessageParameter = sentmessage != null ?
                new ObjectParameter("sentmessage", sentmessage) :
                new ObjectParameter("sentmessage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_messagessend_Result>("sp_messagessend", typeParameter, phone, sentmessageParameter);
        }
    
        public virtual ObjectResult<string> sp_receivedmessages(string phone, string choice, string returnmessage)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var choiceParameter = choice != null ?
                new ObjectParameter("choice", choice) :
                new ObjectParameter("choice", typeof(string));
    
            var returnmessageParameter = returnmessage != null ?
                new ObjectParameter("returnmessage", returnmessage) :
                new ObjectParameter("returnmessage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_receivedmessages", phoneParameter, choiceParameter, returnmessageParameter);
        }
    }
}
