//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilioResponse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class participatinglocation
    {
        public int locationid { get; set; }
        public string locationaddress { get; set; }
        public string participatingfor { get; set; }
        public string active { get; set; }
        public Nullable<int> displayorder { get; set; }
        public Nullable<int> choice { get; set; }
    }
}
