//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilioResponse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class receivedtransaction
    {
        public int receivedtransactionid { get; set; }
        public string phone { get; set; }
        public string Responsereceived { get; set; }
        public Nullable<System.DateTime> datetimereceived { get; set; }
    }
}
