//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilioResponse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class senttransaction
    {
        public int senttransactionid { get; set; }
        public string phone { get; set; }
        public string msgsentfor { get; set; }
        public string msgsent { get; set; }
        public string datetimesent { get; set; }
    }
}
