//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilioResponse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string Password { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string CreatedBy { get; set; }
    }
}
