//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilioResponse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactionstatu
    {
        public int transactionstatusid { get; set; }
        public int transactionid { get; set; }
        public string transactionfor { get; set; }
        public string status { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> statusdatetime { get; set; }
    }
}
